package com.example.liveaction_ext;

public class DummyData {
    public String Data_for_dash() {

//        String result ="{\"success\":true,\"showDummy\":false,\"result\":[{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":12,\"category\":\"Learn\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0,\"variance\":0},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":11,\"category\":\"Fitness\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0,\"variance\":0},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":10,\"category\":\"Finance\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0,\"variance\":0},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":9,\"category\":\"Shopping\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0.5,\"variance\":-0.5},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":8,\"category\":\"Travel\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0,\"variance\":0},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":7,\"category\":\"Social\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0.7,\"variance\":-0.7},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":6,\"category\":\"Music\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":2.2,\"variance\":-2.2},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":5,\"category\":\"Games\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0.3,\"variance\":-0.3},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":4,\"category\":\"Entertainment\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":1.9,\"variance\":-1.9},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":3,\"category\":\"e-Meetings\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0.3,\"variance\":-0.3},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":2,\"category\":\"Email\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":0,\"variance\":0},{\"user_id\":1,\"usage_in_mins\":0,\"usacm_id\":1,\"category\":\"Others\",\"usage_percent\":0,\"last_7_day_usage_in_mins\":2.1,\"variance\":-2.1},{\"user_id\":1,\"usage_in_mins\":24,\"usacm_id\":0,\"category\":\"Idle\",\"usage_percent\":100,\"last_7_day_usage_in_mins\":16,\"variance\":null}]}";
        return "{\"success\":true,\"showDummy\":false,\"result\":[{\"user_id\":1,\"usage_in_mins\":10,\"usacm_id\":12,\"category\":\"Learn\",\"usage_percent\":30,\"last_7_day_usage_in_mins\":15,\"variance\":-5},{\"user_id\":1,\"usage_in_mins\":5,\"usacm_id\":11,\"category\":\"Fitness\",\"usage_percent\":20,\"last_7_day_usage_in_mins\":8,\"variance\":-3},{\"user_id\":1,\"usage_in_mins\":8,\"usacm_id\":10,\"category\":\"Finance\",\"usage_percent\":25,\"last_7_day_usage_in_mins\":12,\"variance\":-4},{\"user_id\":1,\"usage_in_mins\":2,\"usacm_id\":9,\"category\":\"Shopping\",\"usage_percent\":10,\"last_7_day_usage_in_mins\":1.5,\"variance\":0.5},{\"user_id\":1,\"usage_in_mins\":4,\"usacm_id\":8,\"category\":\"Travel\",\"usage_percent\":15,\"last_7_day_usage_in_mins\":3,\"variance\":-1},{\"user_id\":1,\"usage_in_mins\":6,\"usacm_id\":7,\"category\":\"Social\",\"usage_percent\":18,\"last_7_day_usage_in_mins\":5,\"variance\":-1},{\"user_id\":1,\"usage_in_mins\":12,\"usacm_id\":6,\"category\":\"Music\",\"usage_percent\":35,\"last_7_day_usage_in_mins\":10,\"variance\":-2},{\"user_id\":1,\"usage_in_mins\":3,\"usacm_id\":5,\"category\":\"Games\",\"usage_percent\":12,\"last_7_day_usage_in_mins\":2,\"variance\":-1},{\"user_id\":1,\"usage_in_mins\":9,\"usacm_id\":4,\"category\":\"Entertainment\",\"usage_percent\":27,\"last_7_day_usage_in_mins\":7,\"variance\":-2},{\"user_id\":1,\"usage_in_mins\":3,\"usacm_id\":3,\"category\":\"e-Meetings\",\"usage_percent\":10,\"last_7_day_usage_in_mins\":1,\"variance\":-1},{\"user_id\":1,\"usage_in_mins\":2,\"usacm_id\":2,\"category\":\"Email\",\"usage_percent\":8,\"last_7_day_usage_in_mins\":0,\"variance\":0},{\"user_id\":1,\"usage_in_mins\":10,\"usacm_id\":1,\"category\":\"Others\",\"usage_percent\":30,\"last_7_day_usage_in_mins\":5,\"variance\":-5},{\"user_id\":1,\"usage_in_mins\":24,\"usacm_id\":0,\"category\":\"Idle\",\"usage_percent\":100,\"last_7_day_usage_in_mins\":16,\"variance\":0}]}";
    }
}

